server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: task-service-route
          uri: ${TASK_SERVICE_URI}
          predicates:
            - Path=/tasks/**
          filters:
            - JwtValidation

        - id: user-service-route
          uri: ${USER_SERVICE_URI}
          predicates:
            - Path=/users/**
          filters:
            - JwtValidation

        - id: auth-service-route
          uri: ${AUTH_SERVICE_URI}
          predicates:
            - Path=/auth/**
