services:
  app:
    build:
      context: .     # path to Dockerfile
      dockerfile: Dockerfile
    image: taskservice:latest
    container_name: taskservice
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_SQL_INIT_MODE=always
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    networks:
      - internal

networks:
  internal:
    external: true
